### ISSUE TITLE
RPCC Client Path

### ISSUE THREAD

**Issue by alokjain024** [Kudaes/Elevator#2]
I am running in windows 10 version 21H2 (os build 19044.1889)

getting code error

 File "C:\Users\XXXXX\Downloads\Elevator-main\Elevator\Cargo.toml", line 7
    rpcclient = { path = "rpcclient" }
                  ^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
![issue](https://user-images.githubusercontent.com/58162036/187129748-e7ecf979-c1ca-4fc4-a055-58c58f8cbdf7.JPG)

please support

**Comment by Kudaes** [comment]
Hi,
What version of rustc are you running?

**Comment by alokjain024** [comment]
Hi @Kudaes  : i didn't installed the suggested tool (RUST) , is it mandatory to install before running the compiler ?

also, do i need to install as python or standalone installer ?

**Comment by Kudaes** [comment]
Well, this project is composed of a C++ solution (which is not required to do anything with it, cause it is already compiled) and a Rust project. The syntax error that you are receiving comes from the Rust project, and because of that you wont be able to compile it without Rust environment tools installed.

The installation should be pretty straightforward, just download and run the official binary from [here](https://www.rust-lang.org/tools/install). After you have installed Rust, you should be able to compile the project ;)
